export const monitors = [
  {
    id: 1,
    location: 'Assumption University',
    keyword: 'Bang Bo',
    province: 'Samut Prakan',
    imageSrc: 'image0.jpg',
    imageAlt: '',
  },
  {
    id: 14,
    location: 'Khon Kaen University',
    keyword: 'Khon Kaen',
    province: 'Khon Kaen',
    imageSrc: 'image3.jpg',
    imageAlt: 'Monitor at Khon Kaen University',
  },
  {
    id: 15,
    location: 'Hat Yai Hospital',
    keyword: 'Hat Yai',
    province: 'Songkhla',
    imageSrc: 'image4.jpg',
    imageAlt: 'Monitor at Hat Yai Hospital',
  },
  {
    id: 13,
    location: 'Phuket International Airport',
    keyword: 'Airport',
    province: 'Phuket',
    imageSrc: 'image2.jpg',
    imageAlt: 'Monitor at Phuket International Airport',
  },
  {
    id: 12,
    location: 'Chiang Mai University',
    keyword: 'Chiang Mai',
    province: 'Chiang Mai',
    imageSrc: 'image1.jpg',
    imageAlt: 'Monitor at Chiang Mai University',
  },
  {
    id: 11,
    location: 'Ancient City',
    keyword: 'Muang Boran',
    province: 'Samut Prakan',
    imageSrc: 'image1.jpg',
    imageAlt: '',
    imageCredit:
      'Photo by <a href="https://unsplash.com/@pawel_czerwinski?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Pawel Czerwinski</a> on <a href="https://unsplash.com/photos/turned-off-signage-_9dSF0Hwitw?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
  },
  {
    id: 2,
    location: 'Siam Paragon',
    province: 'Bangkok',
    keyword: 'Pathum Wan',
    imageSrc: 'image1.jpg',
    imageAlt: '',
    imageCredit:
      'Photo by <a href="https://unsplash.com/@pawel_czerwinski?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Pawel Czerwinski</a> on <a href="https://unsplash.com/photos/turned-off-signage-_9dSF0Hwitw?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
  },
  {
    id: 3,
    location: 'Chatuchak Market',
    province: 'Bangkok',
    keyword: 'Kamphaeng Phet 2',
    imageSrc: 'image2.jpg',
    imageAlt: '',
    imageCredit:
      '<a href="https://www.freepik.com/free-psd/empty-billboard-city_8952262.htm#query=billboard%20mockup&position=1&from_view=keyword&track=ais_hybrid&uuid=370c6554-b8bd-441b-a0ee-20428438d260">Image by user15285612</a> on Freepik',
  },
  {
    id: 4,
    location: 'MBK Center',
    province: 'Bangkok',
    keyword: 'Phaya Thai, Pathum Wan',
    imageSrc: 'image3.jpg',
    imageAlt: '',
    imageCredit:
      'Photo by <a href="https://unsplash.com/@katetrysh?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Kate Trysh</a> on <a href="https://unsplash.com/photos/rectangular-blank-billboard-Dnkr_lmdKi8?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
  },
  {
    id: 5,
    location: 'Asiatique',
    province: 'Bangkok',
    keyword: 'Charoen Krung',
    imageSrc: 'image4.jpg',
    imageAlt: '',
    imageCredit:
      'Photo by <a href="https://unsplash.com/@bramnaus?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Bram Naus</a> on <a href="https://unsplash.com/photos/black-and-white-street-sign-5fvMWp1r2n0?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
  },
  {
    id: 6,
    location: 'Khaosan',
    province: 'Bangkok',
    keyword: 'Talat Yot',
    imageSrc: 'image5.jpg',
    imageAlt: '',
    imageCredit:
      'Photo by <a href="https://unsplash.com/@bramnaus?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Bram Naus</a> on <a href="https://unsplash.com/photos/white-board-on-black-metal-fence-8M07EF_QGt0?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
  },
  {
    id: 7,
    location: 'Central World',
    province: 'Bangkok',
    keyword: 'Pathum Wan',
    imageSrc: 'image6.jpg',
    imageAlt: '',
    imageCredit:
      'Photo by <a href="https://unsplash.com/@teapowered?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Patrick Robert Doyle</a> on <a href="https://unsplash.com/photos/a-wooden-bench-sitting-next-to-a-white-board-csDVMvtsS50?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
  },
  {
    id: 8,
    location: 'Victory Monument',
    province: 'Bangkok',
    keyword: 'Ratchathewi',
    imageSrc: 'image7.jpg',
    imageAlt: '',
    imageCredit:
      'Photo by <a href="https://unsplash.com/@makitrenko?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Mykyta Kravčenko</a> on <a href="https://unsplash.com/photos/a-billboard-on-the-side-of-the-road-r2Pmvr_7Dec?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
  },
  {
    id: 9,
    location: 'Democracy Monument',
    province: 'Bangkok',
    keyword: 'Phra Nakhon',
    imageSrc: 'image8.jpg',
    imageAlt: '',
    imageCredit:
      'Photo by <a href="https://unsplash.com/@michaeldolejs?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Michael Dolejš</a> on <a href="https://unsplash.com/photos/woman-in-orange-dress-standing-on-sidewalk-during-daytime-2fzYjVFhv20?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
  },
  {
    id: 10,
    location: 'ICONSIAM',
    province: 'Bangkok',
    keyword: 'Charoen Nakhon',
    imageSrc: 'image9.jpg',
    imageAlt: '',
    imageCredit:
      'Photo by <a href="https://unsplash.com/@whodunelson?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Nelson Ndongala</a> on <a href="https://unsplash.com/photos/different-vehicles-on-road-near-buildings-with-billboards-during-daytime-6VBVp-V0txQ?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
  },
]
